"""empty message

Revision ID: 154df29e8189
Revises: 
Create Date: 2022-05-15 13:49:31.684685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154df29e8189'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sprite', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('attack', sa.String(), nullable=True),
    sa.Column('hp', sa.String(), nullable=True),
    sa.Column('defense', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('icon', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('poke_team',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon'], ['pokemon.pokemon_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pokemon')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poke_team')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
