"""empty message

Revision ID: a94b6d2578ab
Revises: 4a4a252593a3
Create Date: 2022-05-14 21:17:51.350505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94b6d2578ab'
down_revision = '4a4a252593a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poke_find',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poke_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poke_id'], ['pokemon.poke_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('poke_master')
    op.drop_table('pokemon_poke_master')
    op.add_column('pokemon', sa.Column('exp', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('attack', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('defense', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('ability', sa.String(), nullable=True))
    op.add_column('user', sa.Column('win', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('loss', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'loss')
    op.drop_column('user', 'win')
    op.drop_column('pokemon', 'ability')
    op.drop_column('pokemon', 'defense')
    op.drop_column('pokemon', 'attack')
    op.drop_column('pokemon', 'exp')
    op.create_table('pokemon_poke_master',
    sa.Column('poke_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poke_id'], ['pokemon.poke_id'], name='pokemon_poke_master_poke_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['poke_master.user_id'], name='pokemon_poke_master_user_id_fkey'),
    sa.PrimaryKeyConstraint('poke_id', 'user_id', name='pokemon_poke_master_pkey')
    )
    op.create_table('poke_master',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='poke_master_pkey')
    )
    op.drop_table('poke_find')
    # ### end Alembic commands ###
